version: "3"

vars:
  K8S_VERSION: v1.30.5
  INFRA_NAMESPACE: infra

tasks:
  boot:
    cmds:
      - minikube start --kubernetes-version {{.K8S_VERSION}}
      - kubectx minikube

  ingress:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v4.0.0/deploy/crds.yaml
      - cmd: |
          helm upgrade --install ingress-nginx \
            -n {{.INFRA_NAMESPACE}} --create-namespace \
            oci://ghcr.io/nginxinc/charts/nginx-ingress --version 2.0.0

  expose:
    cmds:
      - minikube tunnel

  mongo:
    cmds:
      - cmd: |
          helm upgrade --install mongodb \
            -n {{.INFRA_NAMESPACE}} --create-namespace \
            -f ./mongodb/values.yaml \
            oci://registry-1.docker.io/bitnamicharts/mongodb

  un-mongo:
    cmds:
      - helm uninstall -n {{.INFRA_NAMESPACE}} mongodb

  fw-mongo:
    cmds:
      - kubectl port-forward -n {{.INFRA_NAMESPACE}} svc/mongodb 27017:27017
