version: "3"

vars:
  K8S_VERSION: v1.30.5
  INFRA_NAMESPACE: infra

tasks:
  boot:
    cmds:
      - minikube start --kubernetes-version {{.K8S_VERSION}}
      - kubectx minikube

  ingress:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v4.0.0/deploy/crds.yaml
      - cmd: |
          helm upgrade --install ingress-nginx \
            -n {{.INFRA_NAMESPACE}} --create-namespace \
            oci://ghcr.io/nginxinc/charts/nginx-ingress --version 2.0.0

  expose:
    cmds:
      - minikube tunnel

  postgres:
    cmds:
      - cmd: |
          helm upgrade --install postgres \
            -n {{.INFRA_NAMESPACE}} --create-namespace \
            -f ./postgres/values.yaml \
            oci://registry-1.docker.io/bitnamicharts/postgresql

  un-postgres:
    cmds:
      - helm uninstall -n {{.INFRA_NAMESPACE}} postgres

  fw-postgres:
    cmds:
      - kubectl port-forward -n {{.INFRA_NAMESPACE}} svc/postgres-postgresql 5432:5432

  ceramic:
    cmd: |
      helm upgrade --install ceramic \
        -n {{.INFRA_NAMESPACE}} --create-namespace \
        -f ./ceramic/values.yaml \
        -f ./ceramic/secrets.yaml \
        ./ceramic

  un-ceramic:
    cmd: helm uninstall -n {{.INFRA_NAMESPACE}} ceramic

  fw-ceramic:
    cmd: kubectl port-forward -n {{.INFRA_NAMESPACE}} svc/js-ceramic 7007:7007
