replicaCount: 1

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

ceramicNetwork: testnet-clay

db:
  name: ceramic
  host: postgres-postgresql.infra

jsceramic:
  image:
    repository: ceramicnetwork/js-ceramic
    pullPolicy: Always
    tag: "latest"

  ipfsHost: http://ceramic-one:5101
  disableComposeDB: false
  indexing:
    dbName: ceramic

  metrics:
    exporterEnabled: false
    prometheusExporterEnabled: true
    prometheusExporterPort: 9464

  reconMode: "true"
  ethRpcUrl: ""
  stateStorePath: "/js-ceramic-data/statestore"
  corsAllowedOrigins: ".*"
  logLevel: 2

ceramicone:
  image:
    repository: public.ecr.aws/r5b3e0r5/3box/ceramic-one
    pullPolicy: Always
    tag: "0.47.0"

  bindAddress: 0.0.0.0:5101
  kademliaParallelism: 1
  kademliaReplication: 6
  localNetworkId: 0
  metricsBindAddress: 0.0.0.0:9465
  recon: "true"
  storeDir: /root/.ceramic-one
  swarmAddresses: /ip4/0.0.0.0/tcp/4001
  rustLog: info,ceramic_one=debug,multipart=error
