apiVersion: v1
kind: Service
metadata:
  name: ceramic-one
spec:
  ports:
    - name: swarm-tcp
      port: 4101
      protocol: TCP
      targetPort: swarm-tcp
    - name: rpc
      port: {{.Values.ceramicone.rpc.port}}
      protocol: TCP
      targetPort: rpc
    - name: metrics
      port: {{.Values.ceramicone.metrics.port}}
      protocol: TCP
      targetPort: metrics
  selector:
    app: ceramic-one
