apiVersion: v1
kind: Service
metadata:
  name: ceramic-one
spec:
  ports:
    - name: swarm-tcp
      port: 4101
      protocol: TCP
      targetPort: swarm-tcp
    - name: rpc
      port: 5101
      protocol: TCP
      targetPort: rpc
    - name: metrics
      port: 9465
      protocol: TCP
      targetPort: metrics
  selector:
    app: ceramic-one
