apiVersion: v1
kind: ConfigMap
metadata:
  name: js-ceramic-env
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "001"
    helm.sh/hook-delete-policy: before-hook-creation

data:
  CERAMIC_DISABLE_COMPOSE_DB: "{{ .Values.jsceramic.disableComposeDB }}"
  CERAMIC_METRICS_EXPORTER_ENABLED: "{{ .Values.jsceramic.metrics.exporterEnabled }}"
  CERAMIC_PROMETHEUS_EXPORTER_ENABLED: "{{ .Values.jsceramic.metrics.prometheusExporterEnabled }}"
  CERAMIC_PROMETHEUS_EXPORTER_PORT: "{{ .Values.jsceramic.metrics.prometheusExporterPort }}"
  CERAMIC_RECON_MODE: "{{ .Values.reconEnabled }}"
  ETH_RPC_URL: "{{ .Values.jsceramic.ethRpcUrl }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-ceramic-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "005"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  daemon-config.json: |
    {
      "anchor": {
        "auth-method": "did"
      },
      "http-api": {
        "cors-allowed-origins": ["{{ .Values.jsceramic.corsAllowedOrigins }}"],
        "admin-dids": ["{{ .Values.secrets.did }}"]
      },
      "indexing": {},
      "ipfs": {
        "mode": "remote",
        "host": "{{ .Values.jsceramic.ipfsHost }}"
      },
      "logger": {
        "log-level": {{ .Values.jsceramic.logLevel }},
        "log-to-files": false
      },
      "metrics": {},
      "network": {
        "name": "{{ .Values.ceramicNetwork }}"
      },
      "node": {
        "private-seed-url": "inplace:ed25519#{{ .Values.secrets.privateKey }}"
      },
      "state-store": {
        "mode": "fs",
        "local-directory": "{{ .Values.jsceramic.stateStorePath }}"
      }
    }
