apiVersion: v1
kind: Service
metadata:
  name: js-ceramic
spec:
  ports:
    - name: api
      port: 7007
      protocol: TCP
      targetPort: api
    - name: metrics
      port: 9464
      protocol: TCP
      targetPort: metrics
  selector:
    app: js-ceramic
  type: ClusterIP
