apiVersion: v1
kind: Service
metadata:
  name: js-ceramic
spec:
  ports:
    - name: api
      port: {{.Values.jsceramic.apiPort}}
      protocol: TCP
      targetPort: api
    - name: metrics
      port: {{.Values.jsceramic.metrics.prometheusExporterPort}}
      protocol: TCP
      targetPort: metrics
  selector:
    app: js-ceramic
  type: ClusterIP
