apiVersion: v1
kind: Secret
metadata:
  name: ceramic-admin
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "001"
stringData:
  private-key: {{.Values.secrets.privateKey}}
  did: {{.Values.secrets.did}}
