apiVersion: v1
kind: Secret
metadata:
  name: ceramic-admin
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "001"
stringData:
  private-key: {{.Values.secrets.privateKey}}
  did: {{.Values.secrets.did}}

---
apiVersion: v1
kind: Secret
metadata:
  name: ceramic-postgres-auth
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "001"
stringData:
  db: {{.Values.db.name}}
  host: {{.Values.db.host}}
  password: {{.Values.secrets.db.password}}
  username: {{.Values.secrets.db.username}}
  uri: "postgresql://{{ .Values.secrets.db.username }}:{{ .Values.secrets.db.password }}@{{.Values.db.host}}/{{ .Values.db.name }}?sslmode=disable"
