apiVersion: v1
kind: Secret
metadata:
  name: ceramic-admin
stringData:
  private-key: "{{ randAlphaNum 32 | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: ceramic-postgres-auth
stringData:
  db: ceramic
  host: postgres
  password: ceramic
  username: ceramic
